//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsertExcelDataToSQL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLocation
    {
        public int MLocationID { get; set; }
        public int LocationID { get; set; }
        public int ManagerID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string Active { get; set; }
    }
}
